# Generated by Django 2.0.4 on 2019-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('phone', models.CharField(max_length=13, verbose_name='电话')),
                ('loan_money', models.DecimalField(decimal_places=4, help_text='单位（万元）', max_digits=12, verbose_name='借款金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '预借款人信息表',
                'verbose_name_plural': '预借款人信息表',
                'db_table': 'api_loan',
            },
        ),
    ]
