# Generated by Django 2.0.4 on 2019-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiloan',
            name='loan_money',
            field=models.DecimalField(decimal_places=4, help_text='单位（万元）', max_digits=12, verbose_name='借款金额(万元)'),
        ),
    ]
